# Generated by Django 4.2.1 on 2023-06-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='vote',
        ),
    ]
